issuer: https://token.actions.githubusercontent.com
subject: repo:shopware/shopware:ref:refs/heads/trunk
claim_pattern:
  job_workflow_ref: shopware/shopware/.github/workflows/05-release.yml@refs/heads/trunk

permissions:
  actions: write
